MERGE INTO player_stats_fact fact
USING player_stats_fact_stg stg
ON fact.PlayerID = stg.PlayerID AND fact.TeamID = stg.TeamID AND fact.MatchID = stg.MatchID
WHEN MATCHED THEN
    UPDATE SET
        IsGoalkeeper = stg.IsGoalkeeper,
        FotmobRating = stg.FotmobRating,
        MinutesPlayed = stg.MinutesPlayed,
        GoalsScored = stg.GoalsScored,
        Assists = stg.Assists,
        TotalShots = stg.TotalShots,
        AccuratePasses = stg.AccuratePasses,
        ChancesCreated = stg.ChancesCreated,
        ExpectedGoals = stg.ExpectedGoals,
        ExpectedGoalsOnTarget = stg.ExpectedGoalsOnTarget,
        ExpectedAssists = stg.ExpectedAssists,
        xGandxA = stg.xGandxA,
        FantasyPoints = stg.FantasyPoints,
        FantasyBonusPoints = stg.FantasyBonusPoints,
        ShotsOnTarget = stg.ShotsOnTarget,
        BigChancesMissed = stg.BigChancesMissed,
        BlockedShots = stg.BlockedShots,
        HitWoodwork = stg.HitWoodwork,
        Touches = stg.Touches,
        TouchesinOppBox = stg.TouchesinOppBox,
        SuccessfulDribbles = stg.SuccessfulDribbles,
        PassesintoFinalThird = stg.PassesintoFinalThird,
        Dispossessed = stg.Dispossessed,
        xGNonPenalty = stg.xGNonPenalty,
        TacklesWon = stg.TacklesWon,
        Clearances = stg.Clearances,
        HeadedClearances = stg.HeadedClearances,
        Interceptions = stg.Interceptions,
        DefensiveActions = stg.DefensiveActions,
        Recoveries = stg.Recoveries,
        DribbledPast = stg.DribbledPast,
        DuelsWon = stg.DuelsWon,
        DuelsLost = stg.DuelsLost,
        GroundDuelsWon = stg.GroundDuelsWon,
        AerialDuelsWon = stg.AerialDuelsWon,
        WasFouled = stg.WasFouled,
        FoulsCommitted = stg.FoulsCommitted,
        ShotMapID = stg.ShotMapID,
        FunFact = stg.FunFact,
        UpdateDate = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        PlayerID,
        TeamID,
        MatchID,
        IsGoalkeeper,
        FotmobRating,
        MinutesPlayed,
        GoalsScored,
        Assists,
        TotalShots,
        AccuratePasses,
        ChancesCreated,
        ExpectedGoals,
        ExpectedGoalsOnTarget,
        ExpectedAssists,
        xGandxA,
        FantasyPoints,
        FantasyBonusPoints,
        ShotsOnTarget,
        BigChancesMissed,
        BlockedShots,
        HitWoodwork,
        Touches,
        TouchesinOppBox,
        SuccessfulDribbles,
        PassesintoFinalThird,
        Dispossessed,
        xGNonPenalty,
        TacklesWon,
        Clearances,
        HeadedClearances,
        Interceptions,
        DefensiveActions,
        Recoveries,
        DribbledPast,
        DuelsWon,
        DuelsLost,
        GroundDuelsWon,
        AerialDuelsWon,
        WasFouled,
        FoulsCommitted,
        ShotMapID,
        FunFact,
        InsertDate,
        UpdateDate
    ) VALUES (
        stg.PlayerID,
        stg.TeamID,
        stg.MatchID,
        stg.IsGoalkeeper,
        stg.FotmobRating,
        stg.MinutesPlayed,
        stg.GoalsScored,
        stg.Assists,
        stg.TotalShots,
        stg.AccuratePasses,
        stg.ChancesCreated,
        stg.ExpectedGoals,
        stg.ExpectedGoalsOnTarget,
        stg.ExpectedAssists,
        stg.xGandxA,
        stg.FantasyPoints,
        stg.FantasyBonusPoints,
        stg.ShotsOnTarget,
        stg.BigChancesMissed,
        stg.BlockedShots,
        stg.HitWoodwork,
        stg.Touches,
        stg.TouchesinOppBox,
        stg.SuccessfulDribbles,
        stg.PassesintoFinalThird,
        stg.Dispossessed,
        stg.xGNonPenalty,
        stg.TacklesWon,
        stg.Clearances,
        stg.HeadedClearances,
        stg.Interceptions,
        stg.DefensiveActions,
        stg.Recoveries,
        stg.DribbledPast,
        stg.DuelsWon,
        stg.DuelsLost,
        stg.GroundDuelsWon,
        stg.AerialDuelsWon,
        stg.WasFouled,
        stg.FoulsCommitted,
        stg.ShotMapID,
        stg.FunFact,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ); 