MERGE INTO player_shotmap_fact fact
USING player_shotmap_fact_stg stg
ON fact.MatchID = stg.MatchID AND fact.ShotMapID = stg.ShotMapID AND fact.PlayerID = stg.PlayerID
WHEN MATCHED THEN
    UPDATE SET
        EventType = stg.EventType,
        xPosition = stg.xPosition,
        yPosition = stg.yPosition,
        Minute = stg.Minute,
        IsBlocked = stg.IsBlocked,
        IsOnTarget = stg.IsOnTarget,
        BlockedXPosition = stg.BlockedXPosition,
        BlockedYPosition = stg.BlockedYPosition,
        GoalCrossedYPosition = stg.GoalCrossedYPosition,
        GoalCrossedZPosition = stg.GoalCrossedZPosition,
        ExpectedGoals = stg.ExpectedGoals,
        ExpectedGoalsOnTarget = stg.ExpectedGoalsOnTarget,
        ShotType = stg.ShotType,
        Situation = stg.Situation,
        Period = stg.Period,
        IsOwnGoal = stg.IsOwnGoal,
        OnGoalShotX = stg.OnGoalShotX,
        OnGoalShotY = stg.OnGoalShotY,
        IsSavedOffLine = stg.IsSavedOffLine,
        TeamColor = stg.TeamColor,
        IsPenalty = stg.IsPenalty,
        NewScore = stg.NewScore,
        AssistString = stg.AssistString,
        AssistPlayerID = stg.AssistPlayerID,
        UpdateDate = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        MatchID,
        ShotMapID,
        EventType,
        PlayerID,
        xPosition,
        yPosition,
        Minute,
        IsBlocked,
        IsOnTarget,
        BlockedXPosition,
        BlockedYPosition,
        GoalCrossedYPosition,
        GoalCrossedZPosition,
        ExpectedGoals,
        ExpectedGoalsOnTarget,
        ShotType,
        Situation,
        Period,
        IsOwnGoal,
        OnGoalShotX,
        OnGoalShotY,
        IsSavedOffLine,
        TeamColor,
        IsPenalty,
        NewScore,
        AssistString,
        AssistPlayerID,
        InsertDate,
        UpdateDate
    ) VALUES (
        stg.MatchID,
        stg.ShotMapID,
        stg.EventType,
        stg.PlayerID,
        stg.xPosition,
        stg.yPosition,
        stg.Minute,
        stg.IsBlocked,
        stg.IsOnTarget,
        stg.BlockedXPosition,
        stg.BlockedYPosition,
        stg.GoalCrossedYPosition,
        stg.GoalCrossedZPosition,
        stg.ExpectedGoals,
        stg.ExpectedGoalsOnTarget,
        stg.ShotType,
        stg.Situation,
        stg.Period,
        stg.IsOwnGoal,
        stg.OnGoalShotX,
        stg.OnGoalShotY,
        stg.IsSavedOffLine,
        stg.TeamColor,
        stg.IsPenalty,
        stg.NewScore,
        stg.AssistString,
        stg.AssistPlayerID,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ); 